identifier_name:
    excluded: ["id", "a", "b", "c", "i", "j", "x", "y", "z"]

disabled_rules:
    - redundant_discardable_let
    - line_length
    - void_function_in_ternary

trailing_comma:
    mandatory_comma: true

opt_in_rules:
  - force_unwrapping
